### ISSUE TITLE
Merged curations not showing up in ClearlyDefined

### ISSUE THREAD

**Issue by ariel11** [clearlydefined/service#604]
Hi - the PR for the below components says it has been "merged," however the curated license in that PR is not showing up for the component in ClearlyDefined and consequently, not showing up when @tplunk runs the NOTICE tool. It appears there is a bug.  FYI @geneh 
•  
nuget/nuget/-/microsoft.netcore.platforms/3.0.0-preview8.19405.3
•  nuget/nuget/-/microsoft.win32.registry.accesscontrol/4.6.0-preview8.19405.3
•  nuget/nuget/-/microsoft.win32.registry/4.6.0-preview8.19405.3
•  nuget/nuget/-/microsoft.win32.systemevents/4.6.0-preview8.19405.3
•  nuget/nuget/-/microsoft.windows.compatibility/3.0.0-preview8.19405.3
•  nuget/nuget/-/njsonschema/10.0.22
•  nuget/nuget/-/runtime.native.system.data.sqlclient.sni/4.6.0-preview8.19405.3
•  nuget/nuget/-/runtime.native.system.io.ports/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.codedom/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.componentmodel.composition.registration/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.componentmodel.composition/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.configuration.configurationmanager/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.data.odbc/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.data.oledb/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.data.sqlclient/4.7.0-preview8.19405.3
•  nuget/nuget/-/system.diagnostics.eventlog/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.diagnostics.performancecounter/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.directoryservices.accountmanagement/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.directoryservices.protocols/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.directoryservices/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.drawing.common/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.io.filesystem.accesscontrol/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.io.packaging/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.io.ports/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.management/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.net.http.winhttphandler/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.reflection.context/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.reflection.emit.ilgeneration/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.reflection.emit.lightweight/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.reflection.emit/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.runtime.caching/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.runtime.compilerservices.unsafe/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.runtime.windowsruntime.ui.xaml/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.runtime.windowsruntime/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.security.accesscontrol/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.security.cryptography.cng/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.security.cryptography.pkcs/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.security.cryptography.protecteddata/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.security.cryptography.xml/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.security.permissions/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.security.principal.windows/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.servicemodel.syndication/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.serviceprocess.servicecontroller/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.text.encoding.codepages/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.text.encodings.web/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.threading.accesscontrol/4.6.0-preview8.19405.3
•  nuget/nuget/-/system.windows.extensions/4.6.0-preview8.19405.3

**Comment by geneh** [comment]
@ignacionr Could you please check this one?

**Comment by ariel11** [comment]
@ignacionr / @geneh - is there any update?

**Comment by ariel11** [comment]
@ignacionr - There is another batch of links with this same issue.

•	nuget/nuget/-/microsoft.aspnetcore.authentication.microsoftaccount/2.2.0
•	nuget/nuget/-/microsoft.aspnetcore.http.connections.common/1.1.0
•	nuget/nuget/-/microsoft.aspnetcore.http.connections/1.1.0
•	nuget/nuget/-/microsoft.aspnetcore.http/2.2.2
•	nuget/nuget/-/microsoft.aspnetcore.httpspolicy/2.2.0
•	nuget/nuget/-/microsoft.aspnetcore.identity/2.2.0
•	nuget/nuget/-/microsoft.aspnetcore.owin/2.2.0
•	nuget/nuget/-/microsoft.extensions.configuration.binder/2.2.4
•	nuget/nuget/-/microsoft.extensions.configuration.environmentvariables/2.2.4
•	nuget/nuget/-/microsoft.extensions.fileproviders.embedded/2.2.0
•	nuget/nuget/-/microsoft.extensions.hosting/2.2.0
•	nuget/nuget/-/microsoft.extensions.identity.core/2.2.0
•	nuget/nuget/-/microsoft.extensions.logging.tracesource/2.2.0
•	nuget/nuget/-/microsoft.extensions.options.dataannotations/2.2.0
•	nuget/nuget/-/system.net.http.winhttphandler/4.4.0
•	nuget/nuget/-/system.net.websockets.websocketprotocol/4.5.3
•	nuget/nuget/-/system.reflection.dispatchproxy/4.4.0

**Comment by ignacionr** [comment]
For issues related with PRs, it would help a lot to have the PR number. Next time?

**Comment by ignacionr** [comment]
Taken a couple of the cited components, one from the first report, one from the second report.

![image](https://user-images.githubusercontent.com/1210985/63696752-9505e180-c845-11e9-9fed-5631e0d9e9fb.png)

Currently, I am thinking that the issue maybe simply that the definition response is cached on CDN. In 2 hours it flushes automatically, or it can be done manually; we also gave it a try to pushing refreshes by "tag" but turned out our CDN plan won't allow this functionality.

**Comment by ignacionr** [comment]
Yes that looks odd, and does not seem related to cache. Let me give it another look.

**Comment by ignacionr** [comment]
Will do; I am finishing two other bugs and will look into this in the next few hours. Thanks for your patience.

**Comment by fossygirl** [comment]
@ignacionr checking in on this again.

**Comment by ignacionr** [comment]
OK, @ariel11 can you identify a second PR with a similar condition to compare to? I want to make sure I am looking at the same thing.
Also if you think it would help, I am available for a short meeting with screen sharing.

**Comment by ariel11** [comment]
@ignacionr - sure.  Also, for any of the components above, if you look them up in ClearlyDefined, and go into the "dig into this definition," it will give you the associated PR.  So, randomly looking at this one nuget/nuget/-/microsoft.extensions.options.dataannotations/2.2.0, it still says NOASSERTION when here is the merged PR - https://github.com/clearlydefined/curated-data/pull/2334.  Thank you
![image](https://user-images.githubusercontent.com/17935946/63977223-1937af00-ca68-11e9-9363-16a6023a4ba7.png)

**Comment by ignacionr** [comment]
OK

Just to discard issues with the schema, I checked the [file of reference](https://github.com/clearlydefined/curated-data/blob/ce51402f187b5134615c227950a72899a28c8166/curations/nuget/nuget/-/microsoft.extensions.options.dataannotations.yaml) against [the current schema](https://github.com/clearlydefined/service/blob/08f1623a38ff9cd99683a2f7fcc19bbe12538f50/schemas/curation-1.0.json), and it does check as is.

**Comment by ignacionr** [comment]
@geneh kindly assist me if possible; we would need someone authenticated with ```curate``` permission to hit the ```/sync``` resource with an empty POST as described [here](https://github.com/clearlydefined/service/blob/5b0f794794efdba62f9cfa9d78c76aedfeb66851/routes/curations.js#L88).
After that gets hit, we should receive some [log messages](https://github.com/clearlydefined/service/blob/e4b426e0e0a45ddb02c6a5dc92eb2e5fe7f5abfe/providers/curation/github.js#L67), from which we would need to try figure out if the PR number 2334 appears (call it option A).

In case the PR does not appear, we should still see the effect of manually removing the cache item nuget/nuget/-/microsoft.extensions.options.dataannotations/2.2.0. If this resolves the definition (by recomputing it) call it option B.

My understanding is that if we get ```option A``` this means that the service went down somehow before completely saving/merging the curation. If we get ```option B``` and a resolution by removing the cache item, then it means that the service went to the point of saving the curation (this is more consistent with what we see) but did not get to removing the cache, or somehow did not identify correctly the correct coordinates to invalidate. If there was no solution with removing the cache, then we are at ```option C``` which means that there is something wrong when recreating that definition with the merge of the curation; just in case this is the problem, I am manually testing that process.

**Comment by geneh** [comment]
@ignacionr I ran POST https://api.clearlydefined.io/curations/sync with Authorization:Bearer <secret> and got
```
{
    "status": "OK"
}
```
I don't see any `Backfilling contribution for` log messages.
Let's have a working session if necessary.

**Comment by fossygirl** [comment]
@ignacionr How is this going?

**Comment by ignacionr** [comment]
Rechecking after @geneh helped with sync...

**Comment by fossygirl** [comment]
@ignacionr How's this going? Do you need further info to investigate?

**Comment by ignacionr** [comment]
@fossygirl for now I'm good; I'm using the definitions accessible through API on the production environment, and the curations on PRs, to reproduce; it will take a few more hours to have a result.

**Comment by ignacionr** [comment]
OK it seems this is related to #589 

Since the implementation of #594 the casing is coordinated (as per the issue requesting this) with the request, as opposed to reflect what is on our storage.

Somehow, the URL used to obtain the definitions differed in casing for the package (noticeably, this is not reproducible by using the main web UI which does the requests based upon suggestions, which come with casing that matches our storage).

At some point, a match is made that requires casing -that match fails.

We could resolve this at different levels. Alternatives off the top of my hat.

- revert what was requested as #589 in view of its implications
- make it so a specific additional check is made when the definition is to be used for curations (e.g. add a ```casing=original``` parameter
- make it so the matching between definitions and curations is case insensitive

In any case, this is a sensitive matter because issues like this may be piling up as we discuss.

Input from @fossygirl @iamwillbar @geneh is appreciated.

**Comment by jeffmendoza** [comment]
As I see it, here are the steps we need to take:

- [x] Revert #594 to fix the issue now.
- [ ] Audit recent curation PRs to see if they were affected.
- [ ] Evaluate the motivation for #589 and decide if it should still be implemented.
- [ ] If needed, re-implement #589 without causing this issue. Possibly:
    > * make it so a specific additional check is made when the definition is to be used for curations (e.g. add a casing=original parameter)
    > * make it so the matching between definitions and curations is case insensitive

**Comment by iamwillbar** [comment]
I can speak to the motivation for #589, the intent of the `POST` is to send a list of coordinates and get back a set of results, you need some way to correlate which response relates to which coordinate you requested, and this is easiest if the key in the response matches what you put in the request (the normalized content can live inside the object but the key should match what you asked for).

**Comment by fossygirl** [comment]
@ignacionr How is the progess on this?

**Comment by ignacionr** [comment]
Hey @fossygirl , as discussed on the Implementation discord channel, we will have a discussion today about this particular issue.

The request was to make it easy to match the multiple items on a response, with the multiple items on a request when using the ```/definitions``` POST endpoint.
I would be happy to offer two options to cope with the request that started this problem.
- since the definitions request is an array, we can add an indication for each result, of the array index they belong to, or otherwise
- we can offer a parameter into the same endpoint such as ```/definitions?casing=request``` to force the post processing that changes the results obtained to match request casing.

With either of those approaches, there would be no need to change other parts of the system, and still we would be fulfilling the intent of #589 
I still think it's worth discussing orally, so to align all the parties, avoid excessive verbosity on these issues comments, and making sure every position is heard.

**Comment by geneh** [comment]
@ignacionr I prefer the second option. Should it be something like `/definitions?preserveCasing=true` or `/definitions?originalCasing=true`?

**Comment by ignacionr** [comment]
The problem with ```preserve``` and ```original``` is that you're never sure if you're talking about the original request, or the original data on our storage source.

**Comment by ignacionr** [comment]
As discussed at our meeting, we will make it so there is an optional route query parameter ```matchCasing=false``` which will allow some parts of the UI to request the original/underlying casing as it comes from storage.

**Comment by ignacionr** [comment]
This was completed; kindly reopen if we find new instances of this problem.

**Comment by geneh** [comment]
@ignacionr Has the following been done?

> Audit recent curation PRs to see if they were affected.

**Comment by ignacionr** [comment]
That’s a good idea. Will check in the latest curation PRs entered.
