### ISSUE TITLE
Proposal - Add GitLab as a source for Git components

### ISSUE THREAD

**Issue by nellshamrell** [clearlydefined/service#842]
# GitLab

This issue proposes adding GitLab as an additional source (GitHub is the only current source) for Git components on ClearlyDefined. I've written up a case for it based on the criteria discussed in [this issue](https://github.com/clearlydefined/service/issues/819). I've also opened a [pull request to add this criteria to the ClearlyDefined docs](https://github.com/clearlydefined/clearlydefined/pull/141)

## Discoverability

_How are the packages for this language discovered? Is the repository searched by the build tooling without the user having to customize their client?_

GitLab has a [UI which allows for searching the public GitLab instance](https://gitlab.com/public) as well as [an API that allows for searching](https://docs.gitlab.com/ee/api/search.html).

## Primary Source

_Is this the primary repository that the package is published to? Or is this repository a mirror of an existing repository? We should always harvest from primary sources._

My understanding is that, when someone uses GitLab as the repository for their source code, they typically do not use GitHub as a source as well. GitLab should be the primary source for git repositories that are uploaded to it.

## Reputability

_Is this repository operated by a reputable organization? What is the purpose behind running this repository? Is there an identifiable team that can be reached in the event of any issues?_

GitLab is a well-known and reputable organziation and has [extensive documentation](https://gitlab.com/help) as well as [support available through a subscription](https://about.gitlab.com/pricing/), this is similar to GitHub.

## Security

_How secure is the repository? Is there a team that is available to handle issues in a timely manner when they arise? How fast do they respond to issues, such as when a security vulnerability is planted as a backdoor in a package?_

GitLab does have [a security team available and appears to take security seriously](https://about.gitlab.com/handbook/engineering/security/)

## Automation

_Does the repository support an API to support pulling of information? If not, is the package index organized in a schematized format that can programmatically queried using the package name and version and queried using HTTP(s). When using HTTP to mine data, ClearlyDefined should check for the existence of robots.txt or robot headers that indicate such mining is unacceptable. How much effort is it to automate the process?_

GitLab has [an API available](https://docs.gitlab.com/ee/api/api_resources.html) that should fit all our needs.

## Relationship

_Reach out to the organization that maintains the repository to indicate that ClearlyDefined wishes to harvest data from their repository, with an explanation on how harvesting is done, what the data is used for and how much additional traffic this could result in. Identify/Resolve any concerns and provide a contact from ClearlyDefined in the event they need to support in case of an issue._

Once we have a prototype of our ClearlyDefined code in place, I will reach out to GitLab to introduce them to ClearlyDefined and let them know what we plan to do. I don't anticipate this being an issue, but it will be good to let them know and establish a relationship with them.

**Comment by nellshamrell** [comment]
We discussed this at the community meeting this past Mon and everyone seemed agreed that this was a good idea! I'll start implementing this shortly!

**Comment by nellshamrell** [comment]
# Implementation plan 

(Subject to change)
(Based on the changes made when maven.google.com was added as a source for maven components in [this pull request](https://github.com/clearlydefined/service/pull/829/files))

## Service

### Core Changes

### Related Changes

- [ ] Add `originGitLab` route to [app.js](https://github.com/clearlydefined/service/blob/1d735b3bb693af4c2a982873a8079d5dd721d575/app.js#L132)
- [ ] Add handling for building the source url for a GitLab component to [lib/utils#buildSourceUrl](https://github.com/clearlydefined/service/blob/1d735b3bb693af4c2a982873a8079d5dd721d575/lib/utils.js#L188)

### Documentation
- [ ] Add GitLab to Provider Registry in [README](https://github.com/clearlydefined/service/blob/master/README.md#provider-registry)

**Comment by nellshamrell** [comment]
# Notes

```bash
$ curl https://api.clearlydefined.io/origins/github/clearlydefined/service
[{"id":"clearlydefined/service"}]
```

```bash
curl https://api.clearlydefined.io/origins/github/clearlydefined/service/revisions
[]
```

**Comment by nellshamrell** [comment]
Closing because this has been completed with #850 :)
